import React from "react";
import { CourseDetailPage } from "@/components/ui/CourseDetailPage";

interface Props {
  slug?: string;
}

export default function AdvancedExcelTrainingPage({ slug = "advanced-excel-training" }: Props) {
  return <CourseDetailPage slug={slug} title="Advanced Excel Training with Gen AI" badge="Popular" duration="4 weeks" tagline="Practical Excel skills for teams and professionals." description="A practical Excel Basic to Advanced program for working professionals and teams. Covers productivity tools, formulas, lookup, Pivot Tables, Power Query, dashboards, sheet security and Gen AI workflows using real business scenarios."
    brochureRequestTitle="Advanced Excel Training with Gen AI"
    outcomes={["Clean messy Excel data using Flash Fill, Text to Columns and Power Query","Write lookup, logical, conditional and dynamic array formulas","Build Pivot Table based MIS reports, aging reports and KPI scorecards","Create automated reporting workflows from files, folders and multiple sheets","Use Goal Seek, Scenario Manager and Solver for business analysis","Apply ChatGPT and Copilot-style Gen AI workflows for formulas, macros and data analysis"]}
    whoFor={["Employees and professionals who use Excel for reporting, analysis or operations","Finance, MIS, HR, sales, quality and operations teams","Managers who want teams to move from manual Excel work to structured reporting","Analysts who need Pivot Tables, Power Query, dashboards and automation skills","Working professionals who want practical Excel skills with Gen AI support"]}
    modules={[
      {title:"Week 1 - Excel fundamentals and core functions",topics:["Excel interface and Ribbon productivity","Relative, absolute and mixed references","SUM, AVERAGE, MAX, MIN and COUNT functions","Text, date and time functions","VLOOKUP, HLOOKUP and XLOOKUP","Error handling with IFERROR and IS functions"]},
      {title:"Week 2 - Advanced functions and analysis tools",topics:["IF, Nested IF, AND, OR and NOT","COUNTIFS, SUMIFS and AVERAGEIFS","SUMPRODUCT for advanced filtering","Conditional formatting with formulas","Data validation and dependent dropdowns","Goal Seek, Scenario Manager and Solver"]},
      {title:"Week 3 - Pivot Tables, dynamic arrays and Power Query",topics:["Pivot Tables, Pivot Charts and slicers","Calculated fields and GETPIVOTDATA","UNIQUE, SORT, FILTER and SEQUENCE","Name Manager, INDIRECT and OFFSET","Power Query ETL and folder combining","Power Pivot relationships and data model basics"]},
      {title:"Week 4 - Dashboards, Gen AI and sheet security",topics:["Dashboard layout and KPI design","Pareto, trend and variance visuals","ChatGPT for Excel formulas and analysis","AI-assisted macro and workflow support","Worksheet and workbook protection","Final business dashboard assessment"]},
    ]}
    detailedOutline={[
      {week:"Week 1",module:"Excel Interface, Fundamentals and Productivity Tools",topics:["Excel interface, Ribbon and QAT customization","Workbook vs worksheet management","Data types: general, number, text, date and time","Relative, absolute and mixed references","AutoFill, Flash Fill and Fill Series","Find and Replace with wildcards","Go To Special for blanks, formulas and visible cells","Remove Duplicates, Freeze Panes and Split Window","Productivity shortcuts"],application:"Clean messy production sheets, remove duplicate data, identify blanks in QC sheets and create structured tables for daily shift reports."},
      {week:"Week 1",module:"Foundational Functions and Lookup Basics",topics:["SUM, AVERAGE, MAX, MIN, COUNT and COUNTA","LEFT, RIGHT, MID, LEN, TRIM, PROPER, UPPER, LOWER, CONCAT and TEXTJOIN","TODAY, NOW, EOMONTH, NETWORKDAYS, WORKDAY and DATEDIF","VLOOKUP, HLOOKUP, XLOOKUP and CHOOSE","IFERROR, ISERROR, ISBLANK, ISTEXT and ISNUMBER"],application:"Extract employee codes and part codes, calculate delays, create employee master lookups and standardize customer or vendor names."},
      {week:"Week 2",module:"Logical, Conditional and Advanced Functions",topics:["IF and Nested IF","AND, OR and NOT","COUNTIF and COUNTIFS","SUMIF and SUMIFS","AVERAGEIF and AVERAGEIFS","SUMPRODUCT","DSUM, DCOUNT and DCOUNTA","Formula-based conditional formatting"],application:"Build quality check pass/fail logic, create multi-criteria production MIS, highlight delayed orders and calculate filtered totals without manual filters."},
      {week:"Week 2",module:"Data Cleaning, Analysis and Scenario Tools",topics:["Text to Columns","Advanced Flash Fill patterns","Single-level, multi-level and custom sorting","Subtotals, grouping and outline","Data validation and dependent dropdowns","Goal Seek","Scenario Manager","Solver","Watch Window and Evaluate Formula"],application:"Create automated dropdowns for production entry, perform sales forecasting, simulate raw material cost impact and optimize scrap cost or resource allocation."},
      {week:"Week 3",module:"Pivot Tables and Advanced Data Summarization",topics:["Pivot Tables from multiple sources","Pivot Table Wizard","Tabular and outline layouts","Date, number and text grouping","Slicers and timelines","Calculated fields and calculated items","GETPIVOTDATA","Pivot Charts including line, column, combo and KPI visuals"],application:"Create daily and weekly production MIS, aging reports, customer-wise and product-wise summaries, regional dashboards and performance scorecards."},
      {week:"Week 3",module:"Advanced Excel Formulas, Dynamic Arrays and Power Query",topics:["Name Manager and dynamic ranges","INDIRECT and OFFSET","UNIQUE, SORT, FILTER, SEQUENCE and RANDARRAY","Legacy and dynamic array formulas","One-variable and two-variable Data Tables","Formula auditing","Power Query ETL","CSV, Excel and folder import","Split, merge, append and unpivot","Power Pivot relationships and keys"],application:"Build dynamic dropdowns, real-time filtered dashboards, sensitivity analysis, monthly templates and automated Power Query pipelines for recurring reports."},
      {week:"Week 4",module:"Dynamic Dashboards and KPI Reporting",topics:["Dashboard concepts and layout planning","Choosing Pareto, trend, variance and KPI visuals","Clean chart formatting","Slicers, timelines and interactivity","Combining Pivot Tables, formulas and visuals"],application:"Build an end-to-end production, sales or quality dashboard, create management-ready KPI scorecards and complete a final assessment dashboard."},
      {week:"Week 4",module:"Gen AI for Excel, ChatGPT Workflows and Sheet Security",topics:["AI-driven productivity in Excel","Limits of traditional Excel functions","ChatGPT and Copilot-style formula support","Analyzing Excel data with ChatGPT","Generating instructions, formulas and macro ideas","Automated workflows using formulas and Power Query","Worksheet and workbook protection","Cell protection and review settings"],application:"Use AI to generate formulas, clean data, draft macro logic, convert business logic into Excel models and protect reports from unwanted changes."},
    ]}
  />;
}
